// 데모 모드(Supabase 키 없음) 전용 목데이터.
// 실서비스(키 설정됨)에서는 절대 쓰지 않는다 — DB 장애 시 가짜 체육관이 예약 가능하게 보이는 것을 막기 위함.
import type { Gym } from "@/lib/gyms";
import type { GymEvent } from "@/lib/events";

export const MOCK_GYMS: Gym[] = [
  {
    id: "gracie-yeoksam",
    name: "그레이시 주짓수 역삼",
    disciplines: ["주짓수"],
    district: "강남구 역삼동",
    address: "서울 강남구 테헤란로 123 지하 1층",
    intro: "초보 환영, 화이트벨트 전용 클래스 운영. 오픈매트 매주 토요일.",
    trialPrice: 0,
    dayPassPrice: 20000,
    monthlyPrice: 180000,
    rating: 4.8,
    reviewCount: 41,
    emoji: "🥋",
    amenities: ["운동복 대여", "수건 제공", "샤워실", "개인 락커"],
    photos: [{ src: "/gyms/gracie-1.jpg", caption: "스파링" }, { src: "/gyms/gracie-2.jpg", caption: "기술 훈련" }, { src: "/gyms/gracie-3.jpg", caption: "오픈매트" }],
    lat: 37.4995539,
    lng: 127.0313935,
    kakaoPlaceId: null,
  },
  {
    id: "ironfist-gangnam",
    name: "아이언피스트 복싱 강남",
    disciplines: ["복싱"],
    district: "강남구 논현동",
    address: "서울 강남구 학동로 45 3층",
    intro: "직장인 새벽반·심야반 운영. 1:1 미트 트레이닝 강점.",
    trialPrice: 10000,
    dayPassPrice: null,
    monthlyPrice: 150000,
    rating: 4.6,
    reviewCount: 27,
    emoji: "🥊",
    amenities: ["운동복 대여", "수건 제공", "샤워실", "글러브·장비 대여"],
    photos: [{ src: "/gyms/ironfist-1.jpg", caption: "미트 트레이닝" }, { src: "/gyms/ironfist-2.jpg", caption: "샌드백 훈련" }, { src: "/gyms/ironfist-3.jpg", caption: "스파링" }],
    lat: 37.5126452,
    lng: 127.0301548,
    kakaoPlaceId: null,
  },
  {
    id: "topteam-seolleung",
    name: "탑팀 MMA 선릉",
    disciplines: ["MMA", "주짓수", "킥복싱"],
    district: "강남구 대치동",
    address: "서울 강남구 선릉로 88 2층",
    intro: "아마추어 대회 출전팀 운영. 입문부터 시합반까지.",
    trialPrice: 0,
    dayPassPrice: 25000,
    monthlyPrice: 200000,
    rating: 4.9,
    reviewCount: 63,
    emoji: "🏆",
    amenities: ["운동복 대여", "샤워실", "개인 락커", "글러브·장비 대여", "주차 가능"],
    photos: [{ src: "/gyms/topteam-1.jpg", caption: "케이지 스파링" }, { src: "/gyms/topteam-2.jpg", caption: "그래플링" }, { src: "/gyms/topteam-3.jpg", caption: "시합반 훈련" }],
    lat: 37.4932422,
    lng: 127.0566935,
    kakaoPlaceId: null,
  },
  {
    id: "muay-thai-sinsa",
    name: "싸바이 무에타이 신사",
    disciplines: ["무에타이", "킥복싱"],
    district: "강남구 신사동",
    address: "서울 강남구 도산대로 210 지하 1층",
    intro: "태국 현지 출신 코치 상주. 여성 회원 비율 높음.",
    trialPrice: 15000,
    dayPassPrice: 20000,
    monthlyPrice: 170000,
    rating: 4.7,
    reviewCount: 35,
    emoji: "🇹🇭",
    amenities: ["수건 제공", "샤워실", "글러브·장비 대여"],
    photos: [{ src: "/gyms/muaythai-1.jpg", caption: "클린치 훈련" }, { src: "/gyms/muaythai-2.jpg", caption: "패드 훈련" }, { src: "/gyms/muaythai-3.jpg", caption: "스파링" }],
    lat: 37.5198382,
    lng: 127.0297655,
    kakaoPlaceId: null,
  },
  {
    id: "wrestling-club-yangjae",
    name: "양재 레슬링 클럽",
    disciplines: ["레슬링", "MMA"],
    district: "서초구 양재동",
    address: "서울 서초구 강남대로 12 4층",
    intro: "엘리트 선수 출신 코치진. 테이크다운 특화 커리큘럼.",
    trialPrice: 0,
    dayPassPrice: null,
    monthlyPrice: 160000,
    rating: 4.5,
    reviewCount: 19,
    emoji: "🤼",
    amenities: ["샤워실", "주차 가능"],
    photos: [{ src: "/gyms/wrestling-1.jpg", caption: "케이지 훈련" }, { src: "/gyms/wrestling-2.jpg", caption: "테이크다운" }, { src: "/gyms/wrestling-3.jpg", caption: "스파링" }],
    lat: 37.472004,
    lng: 127.0374639,
    kakaoPlaceId: null,
  },
  {
    id: "checkmat-apgujeong",
    name: "체크매트 압구정",
    disciplines: ["주짓수"],
    district: "강남구 압구정동",
    address: "서울 강남구 압구정로 77 지하 2층",
    intro: "노기 클래스 매일 운영. 외국인 회원 다수, 원정 환영.",
    trialPrice: 10000,
    dayPassPrice: 25000,
    monthlyPrice: 190000,
    rating: 4.8,
    reviewCount: 52,
    emoji: "🟦",
    amenities: ["운동복 대여", "수건 제공", "샤워실", "개인 락커", "주차 가능"],
    photos: [{ src: "/gyms/checkmat-1.jpg", caption: "노기 롤링" }, { src: "/gyms/checkmat-2.jpg", caption: "기술 훈련" }, { src: "/gyms/checkmat-3.jpg", caption: "오픈매트" }],
    lat: 37.5306686,
    lng: 127.0308092,
    kakaoPlaceId: null,
  },
];

// "YYYY-MM-DD" (로컬 날짜)
function toYmd(d: Date): string {
  const mm = String(d.getMonth() + 1).padStart(2, "0");
  const dd = String(d.getDate()).padStart(2, "0");
  return `${d.getFullYear()}-${mm}-${dd}`;
}

// 내일 이후 첫 번째 해당 요일(0=일 … 6=토) + weeksAhead주
function nextWeekday(dow: number, weeksAhead = 0): string {
  const d = new Date();
  d.setDate(d.getDate() + 1);
  while (d.getDay() !== dow) d.setDate(d.getDate() + 1);
  d.setDate(d.getDate() + weeksAhead * 7);
  return toYmd(d);
}

// 데모 일정은 언제 열어도 "다가오는 이벤트"로 보이도록 오늘 기준 요일로 계산한다.
export const MOCK_EVENTS: GymEvent[] = [
  {
    id: "ev-gracie-openmat-0621",
    gymId: "gracie-yeoksam",
    gymName: "그레이시 주짓수 역삼",
    kind: "오픈매트",
    title: "토요 오픈매트 (초보 환영)",
    date: nextWeekday(6),
    startTime: "14:00",
    fee: 0,
    capacity: 30,
    attendees: 22,
    description:
      "매주 토요일 열리는 오픈매트입니다. 화이트벨트도 부담 없이 참여하세요. 가벼운 롤링 위주, 타 체육관 방문 환영.",
    openToVisitors: true,
  },
  {
    id: "ev-topteam-seminar-0628",
    gymId: "topteam-seolleung",
    gymName: "탑팀 MMA 선릉",
    kind: "세미나",
    title: "레슬링 테이크다운 세미나 (게스트 코치)",
    date: nextWeekday(0, 1),
    startTime: "11:00",
    fee: 30000,
    capacity: 24,
    attendees: 24,
    description:
      "국가대표 출신 게스트 코치의 테이크다운 세미나. MMA·그래플러 모두 환영. 노기 복장 권장.",
    openToVisitors: true,
  },
  {
    id: "ev-checkmat-openmat-0620",
    gymId: "checkmat-apgujeong",
    gymName: "체크매트 압구정",
    kind: "오픈매트",
    title: "노기 오픈매트",
    date: nextWeekday(5),
    startTime: "19:00",
    fee: 10000,
    capacity: null,
    attendees: 0,
    description: "금요일 저녁 노기 오픈매트. 외국인 회원 다수, 다양한 스타일과 롤링 가능.",
    openToVisitors: true,
  },
  {
    id: "ev-ironfist-class-0619",
    gymId: "ironfist-gangnam",
    gymName: "아이언피스트 복싱 강남",
    kind: "특별수업",
    title: "초보 복싱 입문 원데이 클래스",
    date: nextWeekday(4),
    startTime: "20:00",
    fee: 20000,
    capacity: 12,
    attendees: 11,
    description: "스텝·잽·원투 기본기를 하루에 배우는 입문 클래스. 장비 무료 대여.",
    openToVisitors: true,
  },
  {
    id: "ev-muaythai-event-0627",
    gymId: "muay-thai-sinsa",
    gymName: "싸바이 무에타이 신사",
    kind: "행사",
    title: "와이크루 데이 + 회원 친선 스파링",
    date: nextWeekday(6, 1),
    startTime: "18:00",
    fee: 0,
    capacity: 40,
    attendees: 18,
    description: "무에타이 전통 의식 와이크루 시연과 회원 친선 스파링. 관람·체험 모두 환영.",
    openToVisitors: true,
  },
  {
    id: "ev-topteam-comp-0712",
    gymId: "topteam-seolleung",
    gymName: "탑팀 MMA 선릉",
    kind: "대회",
    title: "강남 아마추어 그래플링 오픈 (체급별)",
    date: nextWeekday(0, 3),
    startTime: "10:00",
    fee: 50000,
    capacity: 128,
    attendees: 47,
    description:
      "체급·벨트별 브래킷으로 진행되는 아마추어 그래플링 대회. 검증된 전적으로 기록됩니다.",
    openToVisitors: true,
  },
  {
    id: "ev-gracie-openmat-0628",
    gymId: "gracie-yeoksam",
    gymName: "그레이시 주짓수 역삼",
    kind: "오픈매트",
    title: "토요 오픈매트 (초보 환영)",
    date: nextWeekday(6, 1),
    startTime: "14:00",
    fee: 0,
    capacity: 30,
    attendees: 9,
    description: "매주 토요일 오픈매트. 화이트벨트 환영, 타 체육관 방문 환영.",
    openToVisitors: true,
  },
];
